language: python

python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'

os:
- linux

env:
- ARCH=x86_64
- ARCH=i686

install:
- pip install urllib3 certifi pytz pyflakes faker

script:
- pyflakes minio/*.py || true
- python setup.py install
- python setup.py nosetests
- MINT_MODE=full python tests/functional/tests.py
